### ISSUE TITLE
[Bugs] Build OK but run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [Alex313031/apple-music-desktop#1]
I used these to build the package :
```
nvm use 14
cd apple-music-desktop-0.1.3
sed '/zip/d;/deb/d' -i electron-builder.json
npm install --force
npm run build
npm run distLinux
```
Then I run the package through electron22,I got errors:
```
$ electron22 src/apple-music-desktop-0.1.3/dist/linux-unpacked/resources/app.asar 
[32891:0922/092515.825338:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[32891:0922/092515.825384:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
(node:32891) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'whenReady')
    at /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3/dist/linux-unpacked/resources/app.asar/app.js:299:22
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:32891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
When I directlly run the package,I got this:
```
$ ./src/apple-music-desktop-0.1.3/dist/linux-unpacked/apple-music 
[1]    33058 trace trap (core dumped)  ./src/apple-music-desktop-0.1.3/dist/linux-unpacked/apple-music
```

**Comment by zxp19821005** [comment]
```
$ npm run test

> apple-music-desktop@0.1.3 test /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3
> npm run eslint ; npm run stylelint


> apple-music-desktop@0.1.3 eslint /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3
> eslint "src/**/*.js*"


/home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3/src/app.js
    1:68  error  'shell' is assigned a value but never used        no-unused-vars
    6:7   error  'fs' is assigned a value but never used           no-unused-vars
    7:7   error  'url' is assigned a value but never used          no-unused-vars
   10:7   error  'userLogFile' is assigned a value but never used  no-unused-vars
   24:7   error  'isLinux' is assigned a value but never used      no-unused-vars
   26:7   error  'isMac' is assigned a value but never used        no-unused-vars
  179:41  error  'browserWindow' is defined but never used         no-unused-vars
  183:13  error  'srcURL' is defined but never used                no-unused-vars
  210:13  error  'linkURL' is defined but never used               no-unused-vars

/home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3/src/menu.js
    1:29  error  'components' is assigned a value but never used       no-unused-vars
    1:41  error  'dialog' is assigned a value but never used           no-unused-vars
    1:75  error  'Tray' is assigned a value but never used             no-unused-vars
    3:7   error  'contextMenu' is assigned a value but never used      no-unused-vars
    4:7   error  'Store' is assigned a value but never used            no-unused-vars
    6:7   error  'fs' is assigned a value but never used               no-unused-vars
    7:7   error  'url' is assigned a value but never used              no-unused-vars
   13:5   error  'appVersion' is assigned a value but never used       no-unused-vars
   15:5   error  'electronVersion' is assigned a value but never used  no-unused-vars
   16:5   error  'chromeVersion' is assigned a value but never used    no-unused-vars
   17:5   error  'nodeVersion' is assigned a value but never used      no-unused-vars
   18:5   error  'v8Version' is assigned a value but never used        no-unused-vars
   21:7   error  'isLinux' is assigned a value but never used          no-unused-vars
   52:15  error  'item' is defined but never used                      no-unused-vars
   52:21  error  'focusedWindow' is defined but never used             no-unused-vars
   95:15  error  'e' is defined but never used                         no-unused-vars
  108:15  error  'e' is defined but never used                         no-unused-vars
  121:15  error  'e' is defined but never used                         no-unused-vars

✖ 27 problems (27 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apple-music-desktop@0.1.3 eslint: `eslint "src/**/*.js*"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apple-music-desktop@0.1.3 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zxp-endeavouros/.npm/_logs/2023-09-22T01_35_25_602Z-debug.log

> apple-music-desktop@0.1.3 stylelint /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3
> stylelint "src/**/*.css*"


src/css/about.css
  5:16  ✖  Expected "#000000" to be "#000"    color-hex-length
  6:16  ✖  Expected "#0000ee" to be "#00e"    color-hex-length
 13:18  ✖  Expected "#ffffff" to be "#fff"    color-hex-length
 21:16  ✖  Expected "#ffffff" to be "#fff"    color-hex-length
 29:16  ✖  Unexpected quotes around "Roboto"  font-family-name-quotes
 37:16  ✖  Unexpected quotes around "Roboto"  font-family-name-quotes
 39:3   ✖  Expected "auto auto" to be "auto"  shorthand-property-no-redundant-values
 49:10  ✖  Expected newline after ","         selector-list-comma-newline-after

src/css/index.css
 1:1  ✖  Unexpected empty source             no-empty-source
 2:1  ✖  Expected no more than 1 empty line  max-empty-lines

10 problems (10 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! apple-music-desktop@0.1.3 stylelint: `stylelint "src/**/*.css*"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the apple-music-desktop@0.1.3 stylelint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zxp-endeavouros/.npm/_logs/2023-09-22T01_35_26_048Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! apple-music-desktop@0.1.3 test: `npm run eslint ; npm run stylelint`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the apple-music-desktop@0.1.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zxp-endeavouros/.npm/_logs/2023-09-22T01_35_26_061Z-debug.log
```

**Comment by zxp19821005** [comment]
```
$ npm run start

> apple-music-desktop@0.1.3 start /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3
> electron ./src

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',
  path: '/home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-0.1.3/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',
  spawnargs: [ './src' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apple-music-desktop@0.1.3 start: `electron ./src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apple-music-desktop@0.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zxp-endeavouros/.npm/_logs/2023-09-22T01_36_03_538Z-debug.log
```

**Comment by Alex313031** [comment]
@zxp19821005 You can only use node 14 when using yarn, and the only reason I have that set in the package.json is for windows 7/8/8.1 building support.

For any other os, you should use node 16, in fact it already has an nvmrc file.

You can just use
nvm install && npm install && npm run start

**Comment by Alex313031** [comment]
@zxp19821005 As far as the npm run test, I just pushed 0.1.4 which fixes most of these.

**Comment by zxp19821005** [comment]
Still have errors.
### Use electron22
```
$ electron22 src/apple-music-desktop-main/dist/linux-unpacked/resources/app.asar 
[151391:0922/120205.035757:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[151391:0922/120205.035937:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
(node:151391) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'whenReady')
    at /home/zxp-endeavouros/.cache/paru/clone/apple-music-desktop/src/apple-music-desktop-main/dist/linux-unpacked/resources/app.asar/app.js:427:22
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:151391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
### Run AppImage
```
$ ./src/apple-music-desktop-main/dist/apple-music_0.1.4_x86_64.AppImage 
[1]    151620 trace trap (core dumped)  ./src/apple-music-desktop-main/dist/apple-music_0.1.4_x86_64.AppImage
```
### Directlly run
```
$ ./src/apple-music-desktop-main/dist/linux-unpacked/apple-music 
[1]    151543 trace trap (core dumped)  ./src/apple-music-desktop-main/dist/linux-unpacked/apple-music
```

**Comment by zxp19821005** [comment]
Maybe you can dist a Linux package like deb or rpm?

**Comment by Alex313031** [comment]
@zxp19821005 This is weird.

Can you try updating electron to 25.8.2

You will have to replace 2 instances in the package.json, 2 instances in the src/package.json, and 2 instances in the electron-builder-json.

You can just use find + replace for 22.3.24 > 25.8.2

Then try it.

If it still fucks up, try updating to node 18 by manually running nvm use 18, then (important!), run `npm run burn && npm run clean` before running `npm install`. Those commands will remove all node_modules, dist/, and package-lock.jsons

**Comment by Alex313031** [comment]
@zxp19821005 Also, I noticed you have published alot of my Electron apps on the AUR. Thanks. How did you come across my apps?

**Comment by Alex313031** [comment]
@zxp19821005 I am unable to reproduce. Building and running the app works ok with Node 16 on latest Arch Linux with vanilla kernel and openbox DE.

**Comment by zxp19821005** [comment]
> @zxp19821005 Also, I noticed you have published alot of my Electron apps on the AUR. Thanks. How did you come across my apps?

I found it via https://github.com/topics/electron?o=desc&s=updated .

**Comment by zxp19821005** [comment]
I've sent a request to delete https://aur.archlinux.org/pkgbase/apple-music-desktop , and add a new package to instead https://aur.archlinux.org/packages/apple-music-bin .
But it still run on my PC.I thin I've to check my PC first.

**Comment by Alex313031** [comment]
@zxp19821005 But did you get it to work?

**Comment by zxp19821005** [comment]
No,it still get errors.

**Comment by Alex313031** [comment]
@zxp19821005 What exact OS, desktop environment, window manager are you running. I cant reproduce either in the arch install i mentioned above, or in manjaro.

**Comment by zxp19821005** [comment]
OS : `EndeavourOS`
Desktop : `cinnamon 5.8.4`
Kernel : `6.1.55-1-lts`
Window Manager : `lightdm 1:1.32.0-4`

**Comment by Alex313031** [comment]
@zxp19821005 I will install this in a VM and see if I can reproduce.

**Comment by Alex313031** [comment]
@zxp19821005 IDK man. I recreated your setup in a VM, and still didn't have any problems.

**Comment by PlasticSoup** [comment]
@zxp19821005 If you can try the new PKGBUILD on the AUR, I am curious if you still have any issues.

**Comment by zxp19821005** [comment]
Maybe there was something wrong with my PC.I still got errors.

**Comment by Alex313031** [comment]
@PlasticSoup @zxp19821005 OK I was able to build and run fine before, but now I am getting the exact error you are describing! I'm working on it, but no promises. My first instinct was to upgrade/downagrade Electron, but that doesn't work.

**Comment by PlasticSoup** [comment]
I had the same errors originally described using zxp19821005's PKGBUILD from the AUR. After my changes to the PKGBUILD I was able to build 2.0.5 and have been using it for the past month. (btw thanks for making the program Alex) I pushed a new PKGBUILD just before writing this and 2.1.1 is also working on my system. I have built the package using my Arch install and a clean chroot, both resulting packages work normally. I'm adding my specs and the version info from apple-music-desktop if it's of any help.

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.5-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT

App Version: 2.1.1
OS Type: Linux x64
Electron: 22.3.27
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0

**Comment by Alex313031** [comment]
@PlasticSoup @zxp19821005 I was able to fix issues by upgrading the remote module, and Electron to 28.x.x.

Next version will still be based on electron 22, however the version after that will deprecate windows 7/8/8.1 and will switch to newer electron.

**Comment by Alex313031** [comment]
@zxp19821005 @PlasticSoup  New builds based on Electron 28 > https://github.com/Alex313031/apple-music-desktop/releases/tag/2.1.2
